/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Metadata } from "next";
import Content from "./Content";

export const metadata: Metadata = {
  title: "Users DB",
  description: "Generated by create next app",
};

export default function Users() {
  return <Content/>
}
