import { Metadata } from "next";
import Content from "./Content";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function Page(){
    return <Content/>
}